### ISSUE TITLE
[Feature Request] Adding easier to type directive for hiding comments from source code

### ISSUE THREAD

**Issue by shafayetShafee** [jjallaire/code-visibility#2]
Hello, is it possible to add an easier directive syntax (as done [in this answer](https://stackoverflow.com/a/75143229/10858321) on Stackoverflow for example) for hiding comments in source code from the rendered documents?

**Comment by shafayetShafee** [comment]
Should I Make a PR that enables this feature? 😊

**Comment by jjallaire** [comment]
Sure, that would be great!

**Comment by shafayetShafee** [comment]
Implemented this feature as a separate extension [`hide-comment`](https://github.com/shafayetShafee/hide-comment) as suggested [here](https://github.com/jjallaire/code-visibility/pull/3#issuecomment-1418256090)
